### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Jegersej7** [SteffenCarlsen/OSRS-AutoSwitcher---PvPHelper#3]
Not really an issue, but a suggestion.
If you could change the way the switcher stops it would be alot better for me atleast. I normally use 'Escape' key to go to my inventory and this ends the program, often resulting in me closing it by mistake while playing.

Otherwise the switcher works great!

**Comment by SteffenCarlsen** [comment]
Do you suggest allowing the user to specify which key they want to use to shutdown the autoswitcher?

**Comment by Jegersej7** [comment]
I didn’t know if this was possible, but yes that would be optimal.


________________________________

**Comment by SteffenCarlsen** [comment]
No problem, I will look at implementing easier modification of all available hotkeys without doing a full renew of settings, including allowing the user to modify which hotkey shuts down the switcher.

**Comment by Jegersej7** [comment]
Cool, sounds great.
A quick temp fix could be just to change the stop hotkey to something which is not used as F key in runescape - like 'Delete'

________________________________
Fra: Steffen Carlsen <notifications@github.com>
Sendt: 14. marts 2019 12:11
Til: SteffenCarlsen/OSRS-AutoSwitcher---PvPHelper
Cc: Jegersej7; Author
Emne: Re: [SteffenCarlsen/OSRS-AutoSwitcher---PvPHelper] Suggestion (#3)


No problem, I will look at implementing easier modification of all available hotkeys without doing a full renew of settings, including allowing the user to modify which hotkey shuts down the switcher.

**Comment by SteffenCarlsen** [comment]
Soo, 361 days later I finally got around to fixing this. It's on the master branch currently. I'm working on allowing mouse-keys to work as input keys, after that I will release a new version.
